### ISSUE TITLE
Possibility to install operator into the same namespace as payloads it creates

### ISSUE THREAD

**Issue by afoninsky** [VictoriaMetrics/operator#239]
Currently, when I try to install operator into the same namespace using operatorhub - I receive an error:
```
OwnNamespace InstallModeType not supported, cannot configure to watch own namespace
```

```
# kubectl describe csv victoriametrics-operator.v0.14.1
...
  Install Modes:
    Supported:  false
    Type:       OwnNamespace
    Supported:  false
    Type:       SingleNamespace
    Supported:  false
    Type:       MultiNamespace
    Supported:  true
    Type:       AllNamespaces
```
Question: can we update install modes if there is no any technical restriction for doing it?

Refs:
https://gist.github.com/afoninsky/213f36581e22656bb6c7cda5ccfa2e5e
https://operator-framework.github.io/olm-book/docs/operator-scoping.html#targetnamespaces-and-their-realationship-to-installmodes

**Comment by f41gh7** [comment]
For now, there is technical restriction and operator supports only cluster wide install.

 I think, its possible to support single namespace installation mode, but its a bit complicated.

**Comment by f41gh7** [comment]
Added to the v0.19.0 release.

**Comment by ctml91** [comment]
@f41gh7 Where is this configured? I've installed v0.21.0 from OperatorHub in OpenShift and the only option provided is "all namespaces" and the CSV looks like below. I'm not too sure how to use `WATCH_NAMESPACE` with an OLM install?

My goal is to deploy VM without users/tenants from other namespaces being able to access cluster level resources & metrics (e.g. by deploying their own VM instance, I am not sure if they are still restricted due to RBAC of the VM deployments in their namespace or the operator running globally from my namespace is going to allow them to do that kind of thing). Also if I use same namespace deploy is it still possible to scrape metrics from services in other namespaces?

Thanks in advance!

```
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
```

![image](https://user-images.githubusercontent.com/74685281/148667830-21657016-6861-434d-ba81-47a7d3c6eba5.png)
