### ISSUE TITLE
VictoriaLogs

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/operator#686]
Does the operator support VictoriaLogs? If not, are there plans too?

**Comment by f41gh7** [comment]
Hello, yes, we've such plans, but there is not ETA for it.

And it'll be challenging. Current CRD bundle almost exceed 1MB limit.

**Comment by uhthomas** [comment]
>And it'll be challenging. Current CRD bundle almost exceed 1MB limit.

I think you may actually be okay. There are multiple CRD objects, and the cumulative size is not relevant to the 1M size limit. Only if an individual object exceeds 1M will it be a problem.

https://github.com/kubernetes/kubernetes/issues/82292

**Comment by f41gh7** [comment]
I've made some research. 

 Current  the only way for adding VictoriaLogs - completely remove any k8s server side validation. CRD will have only spec definition with preserve unknown true annotation.

 For actual validation, webhook must be used.

 I propose, to add VictoriaLogs as `Deployment` and use the same behavior as `VMSingle` does. 

 cc @Amper @Haleygo

**Comment by Amper** [comment]
> Current the only way for adding VictoriaLogs - completely remove any k8s server side validation. CRD will have only spec definition with preserve unknown true annotation.
> 
> For actual validation, webhook must be used.

I think it may leads problems for some users due:
- they use CRD specification with different handy k8s tools (like `kubectl explain` / `kubectl explore`).
- they doesn't use webhooks because:
  - it block resource deploy when the operator is not running - pipelines will be failed
  - therefore, this requires HA mode deployment and load scaling
  - require certificates

**Comment by AndrewChubatiuk** [comment]
released in [v0.47.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.0)
