### ISSUE TITLE
Populate VMRule `.status` with information about the vmrule resource

### ISSUE THREAD

**Issue by cskinfill** [VictoriaMetrics/operator#798]
It would be great to have the `.status` of the VMRule resource be populated with information like:
* if the rule matched the schema correctly
* timestamp loaded by vmalert
* etc

**Comment by Haleygo** [comment]
Hello!
>if the rule matched the schema correctly

The CRD Validation should be done by [validation admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) before it's created successfully, see https://github.com/VictoriaMetrics/operator/blob/c720cb4452f386b11de95c24d02a47800246f56d/docs/configuration.md?plain=1#L231
As for other fields that vmalert might validate, the error should stay in vmalert since it's generated by it. Users should find the error in vmalert log.

>timestamp loaded by vmalert

Since vmalert is loading and using the rule, why should we propagate the timestamp to vmrule? And this timestamp could change and be different in different vmalert instances,

**Comment by AndrewChubatiuk** [comment]
released in [v0.47.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.0)
